### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by brettlangdon** [fullcontact/fullcontact.py#2]
It appears that the latest version of `FullContact.py` published on PyPI (`0.0.3`) does not support the `company` endpoint, but the latest version in this repo does.

Would you be willing to publish the latest version in this repo?

**Comment by AMeng** [comment]
Version 0.0.4 pushed to PyPI.
https://pypi.python.org/pypi/FullContact.py/0.0.4

**Comment by AMeng** [comment]
Had an issue with that release. Released 0.0.5 with a quick fix.
https://pypi.python.org/pypi/FullContact.py/0.0.5

**Comment by brettlangdon** [comment]
Thanks!!!!
