### ISSUE TITLE
Missing endpoint for "Lookup by Company Name"

### ISSUE THREAD

**Issue by paladini** [fullcontact/fullcontact.py#4]
I was trying to request the `v2/company/search.json?companyName=fullcontact'` API endpoint without success, so I start to read your code and I found that FullContact.Py does not support this specific endpoint. [Click here to go to the line I'm talking about](https://github.com/fullcontact/fullcontact.py/blob/master/fullcontact/fullcontact.py#L19).

The missing endpoint described above is documented inside the FullContact official documentation, [as you can see here](https://www.fullcontact.com/developer/docs/company/#lookup-by-company-name). There's any plans to implement this missing endpoint?

**Comment by AMeng** [comment]
@paladini endpoint added. Thanks for bringing that to our attention.
